// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxyoayirtfroywgbecwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4eW9heWlydGZyb3l3Z2JlY3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MzIwMDgsImV4cCI6MjA1MTQwODAwOH0.gccLt0BQ74G1xeYB1r3uiMKP-IOzHK0RXqbJm1Y8i_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);